version: "3.8"

services:
  web:
    image: roseunghyeon/smartfarm-back:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=8000

networks:
  app-network:
    driver: bridge
