openapi: 3.0.0
info:
  title: 농산물 가격 정보 API
  description: 농산물 가격 정보 및 예측, 커뮤니티 기능을 제공하는 API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: 메인 서버
  - url: http://localhost:8080
    description: 백엔드 서버

components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: string
        message:
          type: string
    
    User:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        birth_date:
          type: string
          format: date
          nullable: true

    UserCreate:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        birth_date:
          type: string
          format: date
          nullable: true

    LoginData:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    Token:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          default: bearer

    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        category:
          type: string
        community_type:
          type: string
          enum: [gardening, marketplace, freeboard]
        created_at:
          type: string
          format: date-time
        author:
          type: string

    Comment:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        post_id:
          type: integer
        author:
          type: string
        created_at:
          type: string
          format: date-time

    WeatherResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        message:
          type: string

paths:
  /:
    get:
      summary: API 루트 엔드포인트
      responses:
        '200':
          description: 기본 메시지 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /cities:
    get:
      summary: 사용 가능한 도시 목록 조회
      responses:
        '200':
          description: 도시 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      cities:
                        type: array
                        items:
                          type: string
                      mapping:
                        type: object
                  message:
                    type: string

  /weather:
    get:
      summary: 도시별 날씨 정보 조회
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
          description: 도시 이름
      responses:
        '200':
          description: 날씨 정보 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherResponse'

  /predict:
    post:
      summary: 참외 질병 예측
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 예측 결과 반환

  /predictions/{crop}/{city}:
    get:
      summary: 작물 가격 예측
      parameters:
        - name: crop
          in: path
          required: true
          schema:
            type: string
          description: 작물 종류
        - name: city
          in: path
          required: true
          schema:
            type: string
          description: 도시 이름
      responses:
        '200':
          description: 예측 결과 반환

  /auth/register:
    post:
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: 회원가입 성공

  /auth/login:
    post:
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'

  /api/write/create:
    post:
      summary: 게시글 작성
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - category
                - community_type
              properties:
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
                community_type:
                  type: string
                  enum: [gardening, marketplace, freeboard]
      responses:
        '201':
          description: 게시글 작성 성공

  /api/comments/{post_id}:
    get:
      summary: 게시글 댓글 조회
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 댓글 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

  /api/satellite:
    get:
      summary: 한반도 위성 구름 이미지 정보 조회
      responses:
        '200':
          description: 위성 이미지 데이터 반환

  /api/price:
    get:
      summary: 농산물 가격 정보 조회
      responses:
        '200':
          description: 가격 데이터 반환

  /api/market:
    get:
      summary: 시장 정보 조회
      responses:
        '200':
          description: 시장 데이터 반환

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
