name: SmartFarm Backend CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          touch .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
          echo "KMA_API_KEY=${{ secrets.KMA_API_KEY }}" >> .env
          echo "KAMIS_API_KEY=${{ secrets.KAMIS_API_KEY }}" >> .env
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "YOUNG_API_KEY=${{ secrets.YOUNG_API_KEY }}" >> .env
          echo "INFOMATION_API_KEY=${{ secrets.INFOMATION_API_KEY }}" >> .env
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env

      - name: Debug - List files
        run: ls -la

      - name: Sign in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: roseunghyeon/smartfarm-back:latest
          cache-from: type=registry,ref=roseunghyeon/smartfarm-back:buildcache
          cache-to: type=registry,ref=roseunghyeon/smartfarm-back:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check EC2 setup and clean disk space
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clean up disk space
            echo "Cleaning up disk space..."
            sudo docker system prune -af --volumes
            sudo rm -rf /var/snap/docker/common/var-lib-docker/tmp/*
            sudo apt-get clean
            sudo journalctl --vacuum-time=1d

            # Check available space
            df -h

            # Check if Docker is installed and fix permissions
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo snap install docker
            fi

            # Setup Docker permissions
            sudo groupadd docker || true
            sudo usermod -aG docker ubuntu
            sudo chown root:docker /var/run/docker.sock || true
            sudo chmod 666 /var/run/docker.sock || true

            # Restart Docker service
            sudo systemctl restart snap.docker.dockerd || true

            # Create app directory if it doesn't exist
            if [ ! -d "/home/ubuntu/app" ]; then
              mkdir -p /home/ubuntu/app
            fi

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clean up old containers and images
            echo "Cleaning up old containers and images..."
            docker container prune -f
            docker image prune -af

            # Ensure Docker socket permissions are correct
            sudo chmod 666 /var/run/docker.sock

            cd /home/ubuntu/app
            docker-compose -f docker-compose.prod.yml down || true
            docker pull roseunghyeon/smartfarm-back:latest
            docker-compose -f docker-compose.prod.yml up -d
